---
abstract: 'Ability based authorization for Catalyst/DBIx::Class apps, based on Catalyst::Plugin::Authorization::Roles'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  version: 0.77
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authorization-Abilities
requires:
  Catalyst::Exception: 0
  Scalar::Util: 0
  perl: 5.006
  version: 0.77
resources:
  homepage: http://github.com/ido50/Catalyst-Plugin-Authorization-Abilities/tree
  repository: git://github.com/ido50/Catalyst-Plugin-Authorization-Abilities.git
version: v0.30.0
